apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-update-cm
  namespace: ingress-nginx-public
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["ingress-public-ingress-nginx-controller"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-update-cm
  namespace: ingress-nginx-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-update-cm
subjects:
- kind: ServiceAccount
  name: default
  namespace: mail
